-- ==========================================================
-- Project: StreamNova Monthly Performance and Engagement Report
-- File: project_ddl_vorontsov.sql
-- Author: Artyom Vorontsov
-- DB: Oracle
-- ==========================================================

-- =========================
-- Safe drop section
-- =========================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE data_quality_issues CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE usage_sessions CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE payments CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE subscription_events CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE subscriptions CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE plans CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =========================
-- Core master tables
-- =========================

CREATE TABLE users (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name      VARCHAR2(100) NOT NULL,
    email          VARCHAR2(150) NOT NULL UNIQUE,
    region         VARCHAR2(50),
    signup_date    DATE NOT NULL
);

CREATE TABLE plans (
    plan_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name   VARCHAR2(50) NOT NULL,
    price       NUMBER(10,2) NOT NULL CHECK (price >= 0),
    is_active   CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y','N'))
);

-- =========================
-- Subscription lifecycle
-- =========================

CREATE TABLE subscriptions (
    subscription_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER NOT NULL,
    plan_id         NUMBER NOT NULL,
    start_date      DATE NOT NULL,
    end_date        DATE,
    status          VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_sub_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_sub_plan FOREIGN KEY (plan_id) REFERENCES plans(plan_id),
    CONSTRAINT chk_sub_status CHECK (status IN ('ACTIVE','CANCELLED','PAUSED','TRIAL'))
);

-- =========================
-- Subscription events
-- =========================

CREATE TABLE subscription_events (
    event_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id NUMBER NOT NULL,
    event_date      DATE NOT NULL,
    event_type      VARCHAR2(30) NOT NULL,
    old_plan_id     NUMBER,
    new_plan_id     NUMBER,
    old_status      VARCHAR2(20),
    new_status      VARCHAR2(20),
    CONSTRAINT fk_evt_sub FOREIGN KEY (subscription_id) REFERENCES subscriptions(subscription_id),
    CONSTRAINT fk_evt_old_plan FOREIGN KEY (old_plan_id) REFERENCES plans(plan_id),
    CONSTRAINT fk_evt_new_plan FOREIGN KEY (new_plan_id) REFERENCES plans(plan_id),
    CONSTRAINT chk_event_type CHECK (
        event_type IN ('UPGRADE','DOWNGRADE','CANCELLATION','REACTIVATION','TRIAL_CONVERSION')
    )
);

-- =========================
-- Payments / billing
-- =========================

CREATE TABLE payments (
    payment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id NUMBER NOT NULL,
    payment_date    DATE NOT NULL,
    amount          NUMBER(10,2) NOT NULL CHECK (amount >= 0),
    discount_amount NUMBER(10,2) DEFAULT 0 CHECK (discount_amount >= 0),
    currency        CHAR(3) DEFAULT 'EUR',
    CONSTRAINT fk_pay_sub FOREIGN KEY (subscription_id) REFERENCES subscriptions(subscription_id)
);

-- =========================
-- Usage / engagement
-- =========================

CREATE TABLE usage_sessions (
    session_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER NOT NULL,
    session_start  DATE NOT NULL,
    session_end    DATE NOT NULL,
    device_type    VARCHAR2(30),
    watch_minutes  NUMBER NOT NULL CHECK (watch_minutes >= 0),
    CONSTRAINT fk_usage_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT chk_session_time CHECK (session_end >= session_start)
);

-- =========================
-- Data quality helper table
-- =========================

CREATE TABLE data_quality_issues (
    issue_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_date   DATE DEFAULT SYSDATE,
    issue_type   VARCHAR2(50) NOT NULL,
    entity_name  VARCHAR2(50) NOT NULL,
    entity_id    NUMBER,
    description  VARCHAR2(400)
);
